# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Women Techmakers Brasil
title-bold: Women Techmakers
title-normal: Brasil
email: annecrsoares@gmail.com
description: O Women Techmakers é um programa da Google para incentivar as mulheres na área de tecnologia.
baseurl: "/Forty-Jekyll-Theme" # the subpath of your site, e.g. /blog
url: "https://annesoares.github.io" # the base hostname & protocol for your site
author:

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 9

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/gxgbrasil/womentechmakers
gitlab_url:
googleplus_url: https://plus.google.com/communities/100202454944694552166
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/womentechmakers
youtube_url: https://www.youtube.com/user/womentechmakers
website_url: https://www.womentechmakers.com/

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: womentechmakers
# Add one or more of the following
facebook:
  app_id:
  publisher:
  admins:
logo:
google_site_verification:
